# NOTE: to reload de config, prees prefix + I
setw -g mouse on

# window navigation
bind -n M-H previous-window
bind -n M-L next-windo

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -s default-terminal 'xterm-256color'

# dracula customizations
set -g @dracula-plugins "battery weather time"
set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
set -g @dracula-military-time true

run -b '~/.tmux/plugins/tpm/tpm'
